version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: NodeDockerfile
    hostname: web
    working_dir: /app
    command: ["pm2-runtime","--raw" , "--output", "/var/log/web.log", "process.yml"]
    secrets:
      - bot_token
    environment:
      NODE_ENV: production
      TELEGRAM_BOT_TOKEN: /run/secrets/bot_token
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    restart: always
    networks:
      - web

secrets:                        # top level secrets block
    bot_token:
        file: ./token_bot_secret.ini
networks:
  web: